//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"clientes")]
    public partial class Clientes : XPLiteObject
    {
        int fCodigoCliente;
        [Key(true)]
        public int CodigoCliente
        {
            get { return fCodigoCliente; }
            set { SetPropertyValue<int>(nameof(CodigoCliente), ref fCodigoCliente, value); }
        }
        Tiposcliente fTiposCliente_idTiposCliente;
        [Association(@"ClientesReferencesTiposcliente")]
        public Tiposcliente TiposCliente_idTiposCliente
        {
            get { return fTiposCliente_idTiposCliente; }
            set { SetPropertyValue<Tiposcliente>(nameof(TiposCliente_idTiposCliente), ref fTiposCliente_idTiposCliente, value); }
        }
        string fDireccion;
        [Size(145)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fTelefono;
        [Size(45)]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        [Association(@"VentasReferencesClientes")]
        public XPCollection<Ventas> VentasCollection { get { return GetCollection<Ventas>(nameof(VentasCollection)); } }
    }

}
