//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"clientejuridico")]
    public partial class Clientejuridico : XPLiteObject
    {
        int fIdClienteJuridico;
        [Key(true)]
        [Persistent(@"idClienteJuridico")]
        public int IdClienteJuridico
        {
            get { return fIdClienteJuridico; }
            set { SetPropertyValue<int>(nameof(IdClienteJuridico), ref fIdClienteJuridico, value); }
        }
        string fNumeroRuc;
        [Size(45)]
        public string NumeroRuc
        {
            get { return fNumeroRuc; }
            set { SetPropertyValue<string>(nameof(NumeroRuc), ref fNumeroRuc, value); }
        }
        string fNombreEmpresa;
        [Size(145)]
        public string NombreEmpresa
        {
            get { return fNombreEmpresa; }
            set { SetPropertyValue<string>(nameof(NombreEmpresa), ref fNombreEmpresa, value); }
        }
        [Association(@"TiposclienteReferencesClientejuridico")]
        public XPCollection<Tiposcliente> Tiposclientes { get { return GetCollection<Tiposcliente>(nameof(Tiposclientes)); } }
    }

}
