//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"factura")]
    public partial class Factura : XPLiteObject
    {
        int fIdFactura;
        [Key(true)]
        [Persistent(@"idFactura")]
        public int IdFactura
        {
            get { return fIdFactura; }
            set { SetPropertyValue<int>(nameof(IdFactura), ref fIdFactura, value); }
        }
        decimal fSubTotal;
        public decimal SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<decimal>(nameof(SubTotal), ref fSubTotal, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        decimal fIVA;
        public decimal IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<decimal>(nameof(IVA), ref fIVA, value); }
        }
        Tipocomprobante fTipoComprobante_idTipoComprobante;
        [Association(@"FacturaReferencesTipocomprobante")]
        public Tipocomprobante TipoComprobante_idTipoComprobante
        {
            get { return fTipoComprobante_idTipoComprobante; }
            set { SetPropertyValue<Tipocomprobante>(nameof(TipoComprobante_idTipoComprobante), ref fTipoComprobante_idTipoComprobante, value); }
        }
    }

}
