//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"tipocomprobante")]
    public partial class Tipocomprobante : XPLiteObject
    {
        int fIdTipoComprobante;
        [Key(true)]
        [Persistent(@"idTipoComprobante")]
        public int IdTipoComprobante
        {
            get { return fIdTipoComprobante; }
            set { SetPropertyValue<int>(nameof(IdTipoComprobante), ref fIdTipoComprobante, value); }
        }
        string fNombreTipoComprobante;
        [Size(45)]
        public string NombreTipoComprobante
        {
            get { return fNombreTipoComprobante; }
            set { SetPropertyValue<string>(nameof(NombreTipoComprobante), ref fNombreTipoComprobante, value); }
        }
        Ventas fVentas_idVentas;
        [Association(@"TipocomprobanteReferencesVentas")]
        public Ventas Ventas_idVentas
        {
            get { return fVentas_idVentas; }
            set { SetPropertyValue<Ventas>(nameof(Ventas_idVentas), ref fVentas_idVentas, value); }
        }
        [Association(@"FacturaReferencesTipocomprobante")]
        public XPCollection<Factura> Facturas { get { return GetCollection<Factura>(nameof(Facturas)); } }
    }

}
