//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"tiposcliente")]
    public partial class Tiposcliente : XPLiteObject
    {
        int fIdTiposCliente;
        [Key(true)]
        [Persistent(@"idTiposCliente")]
        public int IdTiposCliente
        {
            get { return fIdTiposCliente; }
            set { SetPropertyValue<int>(nameof(IdTiposCliente), ref fIdTiposCliente, value); }
        }
        string fTipoCliente;
        [Size(45)]
        public string TipoCliente
        {
            get { return fTipoCliente; }
            set { SetPropertyValue<string>(nameof(TipoCliente), ref fTipoCliente, value); }
        }
        Clientejuridico fClienteJuridico_idClienteJuridico;
        [Association(@"TiposclienteReferencesClientejuridico")]
        public Clientejuridico ClienteJuridico_idClienteJuridico
        {
            get { return fClienteJuridico_idClienteJuridico; }
            set { SetPropertyValue<Clientejuridico>(nameof(ClienteJuridico_idClienteJuridico), ref fClienteJuridico_idClienteJuridico, value); }
        }
        [Association(@"ClientenaturalReferencesTiposcliente")]
        public XPCollection<Clientenatural> Clientenaturals { get { return GetCollection<Clientenatural>(nameof(Clientenaturals)); } }
        [Association(@"ClientesReferencesTiposcliente")]
        public XPCollection<Clientes> ClientesCollection { get { return GetCollection<Clientes>(nameof(ClientesCollection)); } }
    }

}
