//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"tipoproducto")]
    public partial class Tipoproducto : XPLiteObject
    {
        int fIdTipoProducto;
        [Key(true)]
        [Persistent(@"idTipoProducto")]
        public int IdTipoProducto
        {
            get { return fIdTipoProducto; }
            set { SetPropertyValue<int>(nameof(IdTipoProducto), ref fIdTipoProducto, value); }
        }
        string fNombreTipoProducto;
        [Size(45)]
        public string NombreTipoProducto
        {
            get { return fNombreTipoProducto; }
            set { SetPropertyValue<string>(nameof(NombreTipoProducto), ref fNombreTipoProducto, value); }
        }
        [Association(@"ProductosReferencesTipoproducto")]
        public XPCollection<Productos> ProductosCollection { get { return GetCollection<Productos>(nameof(ProductosCollection)); } }
    }

}
