//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Proyecto_Ferreteria.base_datos_ferreteria
{

    [Persistent(@"usuariosistema")]
    public partial class Usuariosistema : XPLiteObject
    {
        int fIdUsuarioSistema;
        [Key(true)]
        [Persistent(@"idUsuarioSistema")]
        public int IdUsuarioSistema
        {
            get { return fIdUsuarioSistema; }
            set { SetPropertyValue<int>(nameof(IdUsuarioSistema), ref fIdUsuarioSistema, value); }
        }
        string fNombreUsuario;
        [Size(45)]
        public string NombreUsuario
        {
            get { return fNombreUsuario; }
            set { SetPropertyValue<string>(nameof(NombreUsuario), ref fNombreUsuario, value); }
        }
        string fContraseña;
        [Size(255)]
        public string Contraseña
        {
            get { return fContraseña; }
            set { SetPropertyValue<string>(nameof(Contraseña), ref fContraseña, value); }
        }
        string fReportes;
        [Size(45)]
        public string Reportes
        {
            get { return fReportes; }
            set { SetPropertyValue<string>(nameof(Reportes), ref fReportes, value); }
        }
        [Association(@"VentasReferencesUsuariosistema")]
        public XPCollection<Ventas> VentasCollection { get { return GetCollection<Ventas>(nameof(VentasCollection)); } }
    }

}
